    - name: Run Crawler
      run: |
        # 使用 $GITHUB_WORKSPACE 确保在任何情况下都能找到根目录
        cd $GITHUB_WORKSPACE/google_scholar_crawler
        
        pip3 install -r requirements.txt
        python3 main.py
        
        # 确保 results 文件夹存在
        cd $GITHUB_WORKSPACE/google_scholar_crawler/results
        
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
